// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLE_GDQY6KTbWJPXZnL-LUaINYWJXjnmQ',
    appId: '1:532559612269:web:4062b39ec16c6a71ecb264',
    messagingSenderId: '532559612269',
    projectId: 'blood-donation-app-abc8b',
    authDomain: 'blood-donation-app-abc8b.firebaseapp.com',
    storageBucket: 'blood-donation-app-abc8b.appspot.com',
    measurementId: 'G-ZVBBBFD8KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2WZElwykFNwd8DIJSEZXaCSq_-pSg2M4',
    appId: '1:532559612269:android:1c62e10f278aa1f6ecb264',
    messagingSenderId: '532559612269',
    projectId: 'blood-donation-app-abc8b',
    storageBucket: 'blood-donation-app-abc8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcIEo2S1tbxKy4CnzSGqWXviLr2k2L3v8',
    appId: '1:532559612269:ios:9d91ac4039628094ecb264',
    messagingSenderId: '532559612269',
    projectId: 'blood-donation-app-abc8b',
    storageBucket: 'blood-donation-app-abc8b.appspot.com',
    iosClientId: '532559612269-cv0mkk4hld6mucgavii6clvlp4kq3jtf.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcIEo2S1tbxKy4CnzSGqWXviLr2k2L3v8',
    appId: '1:532559612269:ios:e98e8140e84af4e1ecb264',
    messagingSenderId: '532559612269',
    projectId: 'blood-donation-app-abc8b',
    storageBucket: 'blood-donation-app-abc8b.appspot.com',
    iosClientId: '532559612269-smamml89pgq7t0uldtpbgbq5irbb22sd.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1.RunnerTests',
  );
}
